version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - app-network
    restart: unless-stopped
    
  # For development with e2e tests, use a different port to avoid conflicts
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - app-network
    profiles:
      - testing
    restart: unless-stopped
    
  e2e:
    image: mcr.microsoft.com/playwright:v1.52.0
    depends_on:
      - frontend-test
      - backend
    volumes:
      - ./e2e:/e2e
      - ./frontend/node_modules/@playwright:/e2e/node_modules/@playwright
    working_dir: /e2e
    command: npm install && npx playwright test
    networks:
      - app-network
    profiles:
      - testing

networks:
  app-network:
    driver: bridge
