version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ../backend:/app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
